version: "3.8"

services:
  django:
    build: .
    container_name: django
    command: bash -c "python ./manage.py migrate && python ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 0.0.0.0 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres-database
      - POSTGRES_PORT=5432
    depends_on:
      - postgres-database
      - redis
    restart: on-failure

  celery:
    build: .
    container_name: celery
    command: celery -A core worker -l INFO
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - django
      - redis
  postgres-database:
    image: postgres
    container_name: postgres-database
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres-database
      - POSTGRES_PORT=5432
    volumes:
      - postgres_database:/var/lib/postgresql/data/
  redis:
    image: "redis:alpine"
    container_name: redis

volumes:
  postgres_database:
